language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - 1.0.x
    - test
cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/.m2
script:
  - ./mvnw -T 1.5C test -B
install:
  - ./mvnw -T 1.5C install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update --quiet
  - gcloud components install beta pubsub-emulator --quiet
  - gcloud config set project spring-cloud-gcp-ci
after_success:
    - bash <(curl -s https://codecov.io/bash)
